### ISSUE TITLE
What is eRAP_ID?

### ISSUE THREAD

**Issue by rainwala** [powerpak/pathospot-compare#3]
Hello,

I've been throiugh the database fields, and I think I understand all of them except for eRAP_ID and mlst_subtype. What are those?

Also, what types of patient encounter can we store in "encounter_type"?

Thank you.

**Comment by powerpak** [comment]
`eRAP_ID` is actually the field for patient ID. It's named this way because that happens to be the name of one of our [data warehouses](https://erap.mssm.edu).

`mlst_subtype` refers to [MLST](https://pubmlst.org/general.shtml) which is a way to subcategorize strains from the same species based on the sequence of various housekeeping genes. It predates WGS, but is still often useful to get a sense of the diversity in your dataset. Providing this information to pathospot-compare is completely optional and you can leave it blank in your own database.

`encounter_type` is a freeform field, you can include any values you like with the one exception that the value "Hospital Encounter" is treated as an inpatient encounter for the purposes of the filtering in the **dendro-timeline** view.

Update: answers to these questions and more are now in [README-database.md](https://github.com/powerpak/pathospot-compare/blob/master/README-database.md).

**Comment by rainwala** [comment]
Thank you Ted, that makes sense.
